### ISSUE TITLE
Archeon Planks can't be used as Fuel

### ISSUE THREAD

**Issue by Builderdog841** [Silent-Winds/Archeon-Old#30]
They also can't be used for a lot of Crafting Recipes

Solution 1: Add them to the #minecraft_planks tag which might mean that you have to get rid of the custom wooden tools

Solution 2: Add a tag called #archeon_planks, add the planks to it and make the recipes with it manually

**Comment by Aethyus** [comment]
I'll fix the fuel things recipes. 

Well, Archeon Planks don't have to be "compatible" with the Vanilla ones. Why? It's a simple reason, Minecraft (The overworld, the Nether, the End) aren't supposed to be really explored in the Archeon's adventure. It's a totally separated dimension/universe we're making, so we don't need tags. So we don't want to get rid of our tools.
