### ISSUE TITLE
Chinese Translation File for Archeon 1.1.6

### ISSUE THREAD

**Issue by GoldenTotem** [Silent-Winds/Archeon-Old#49]
I have translated this mod to Chinese.  Language file zh_cn.json is in the zip file.

[zh_cn.zip](https://github.com/Silent-Winds/Archeon/files/12142285/zh_cn.zip)

Due to there are too many fabricated(not really exist) words, the translating was very difficulty. But I do my best. Hoping that it may be helpful.

**Comment by Aethyus** [comment]
WOAH! THank you so much! That's so cool to see you translated the mod ^^
Yeah there are tons of fabricated words for things we wanted to create, so yeah, complex. Still, that's awesome of you, thank you so much! And same for all the work you did on the mining speed values, that's great work!! 🧡
